import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
const inter = Inter({ subsets: ["latin"] });
import { auth } from "../auth";
import { SessionProvider } from "next-auth/react";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await auth();
  console.log(session);

  return (
    <html lang="en">
      <body className={inter.className}>

        <SessionProvider session={session}>
          <Navbar />
          {children}
          <Footer />
        </SessionProvider>

      
      </body>
    </html>
  );
}
